//
// Created by coren on 3/27/2022.
//

#ifndef RAYLIB_TESTS_CONSTS_H
#define RAYLIB_TESTS_CONSTS_H

#define GRID_WIDTH 48
#define GRID_HEIGHT 48

#define SCREEN_WIDTH (CELL_SIZE * GRID_WIDTH)
#define SCREEN_HEIGHT (CELL_SIZE * GRID_HEIGHT)



#endif//RAYLIB_TESTS_CONSTS_H
